namespace Web.Models.Factory;

/// <summary>
/// Represents a factory in the production planning system.
/// </summary>
public class Factory
{
    /// <summary>
    /// Unique identifier for the factory.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Name of the factory.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Inputs from other factories.
    /// </summary>
    public List<FactoryInput> Inputs { get; set; } = new List<FactoryInput>();

    /// <summary>
    /// Previous inputs (stored for state comparison).
    /// Since we can't use the previous state in the store, we need to store it here then update it.
    /// </summary>
    public List<FactoryInput> PreviousInputs { get; set; } = new List<FactoryInput>();

    /// <summary>
    /// Products being manufactured in this factory.
    /// </summary>
    public List<FactoryItem> Products { get; set; } = new List<FactoryItem>();

    /// <summary>
    /// Byproducts generated by production.
    /// </summary>
    public List<ByProductItem> ByProducts { get; set; } = new List<ByProductItem>();

    /// <summary>
    /// Power producers in this factory.
    /// </summary>
    public List<FactoryPowerProducer> PowerProducers { get; set; } = new List<FactoryPowerProducer>();

    /// <summary>
    /// Part metrics for all parts used/produced in this factory.
    /// Key is the part ID.
    /// </summary>
    public Dictionary<string, PartMetrics> Parts { get; set; } = new Dictionary<string, PartMetrics>();

    /// <summary>
    /// Building requirements for this factory.
    /// Key is the building ID.
    /// </summary>
    public Dictionary<string, BuildingRequirement> BuildingRequirements { get; set; } = new Dictionary<string, BuildingRequirement>();

    /// <summary>
    /// Whether all requirements are satisfied.
    /// </summary>
    public bool RequirementsSatisfied { get; set; }

    /// <summary>
    /// Export calculator settings.
    /// Key is some identifier for the calculator settings.
    /// </summary>
    public Dictionary<string, ExportCalculatorSettings> ExportCalculator { get; set; } = new Dictionary<string, ExportCalculatorSettings>();

    /// <summary>
    /// Dependencies on other factories.
    /// </summary>
    public FactoryDependency Dependencies { get; set; } = new FactoryDependency();

    /// <summary>
    /// Raw resources used by this factory.
    /// Key is the resource ID.
    /// </summary>
    public Dictionary<string, WorldRawResource> RawResources { get; set; } = new Dictionary<string, WorldRawResource>();

    /// <summary>
    /// Power consumption and production information.
    /// </summary>
    public FactoryPower Power { get; set; } = new FactoryPower();

    /// <summary>
    /// Whether the factory is using raw resources only.
    /// </summary>
    public bool UsingRawResourcesOnly { get; set; }

    /// <summary>
    /// Whether the factory card should be hidden in the UI.
    /// </summary>
    public bool Hidden { get; set; }

    /// <summary>
    /// Whether the factory has any problems.
    /// </summary>
    public bool HasProblem { get; set; }

    /// <summary>
    /// Whether the factory is in sync with the sync state (nullable).
    /// </summary>
    public bool? InSync { get; set; }

    /// <summary>
    /// Sync state for products.
    /// Key is the product ID.
    /// </summary>
    public Dictionary<string, FactorySyncState> SyncState { get; set; } = new Dictionary<string, FactorySyncState>();

    /// <summary>
    /// Sync state for power producers.
    /// Key is the power producer ID.
    /// </summary>
    public Dictionary<string, FactoryPowerSyncState> SyncStatePower { get; set; } = new Dictionary<string, FactoryPowerSyncState>();

    /// <summary>
    /// Display order for UI sorting.
    /// </summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// Tasks associated with this factory.
    /// </summary>
    public List<FactoryTask> Tasks { get; set; } = new List<FactoryTask>();

    /// <summary>
    /// Notes for this factory.
    /// </summary>
    public string Notes { get; set; } = string.Empty;

    /// <summary>
    /// Data version for compatibility tracking.
    /// </summary>
    public string DataVersion { get; set; } = "2025-01-03";
}
